#Server
server:
  port: 8080

spring:
  #Application Info
  application:
    name: users-service
  # DataSource
  datasource:
    url: jdbc:postgresql://localhost:5432/webbysky-tracker-db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  # JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  #Redis
  data:
    redis:
      host: localhost
      port: 6379

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

#Logging
logging:
  pattern:
    console: "%-5level %d{HH:mm:ss} - %msg%n"

#JWT
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token:
    expiration-minutes: 1
  refresh-token:
    expiration-days: 7